"""Pluggable drafting LLM. Providers: anthropic | openai | fallback.

The system runs with NO key: it falls back to deterministic template text so the
whole approve/write-back flow works offline. Drop a key + set LLM_PROVIDER to
upgrade the wording. The LLM only writes language — it never sets risk, never
writes to FHIR, never bypasses a gate.
"""
from __future__ import annotations

import os

PROVIDER = os.getenv("LLM_PROVIDER", "fallback").lower()
ANTHROPIC_MODEL = os.getenv("ANTHROPIC_MODEL", "claude-sonnet-4-6")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4.1-mini")

SYSTEM = (
    "You are a clinical workflow assistant for a primary-care safety-net tool. "
    "Use only the provided context. Be concise and action-oriented. Do not diagnose. "
    "Output a short message a clinician can review and approve."
)


def draft(prompt: str, context: str) -> dict:
    """Return {text, model}. Never raises — falls back to a template on any error."""
    user = f"{prompt}\n\nContext:\n{context}"
    try:
        if PROVIDER == "anthropic" and os.getenv("ANTHROPIC_API_KEY"):
            return _anthropic(user)
        if PROVIDER == "openai" and os.getenv("OPENAI_API_KEY"):
            return _openai(user)
    except Exception as e:  # any SDK/network/key error -> deterministic fallback
        return _fallback(context, note=f"LLM error: {e}")
    return _fallback(context)


def _anthropic(user: str) -> dict:
    import anthropic

    client = anthropic.Anthropic()
    msg = client.messages.create(
        model=ANTHROPIC_MODEL,
        max_tokens=400,
        system=SYSTEM,
        messages=[{"role": "user", "content": user}],
    )
    text = "".join(b.text for b in msg.content if getattr(b, "type", None) == "text").strip()
    return {"text": text, "model": ANTHROPIC_MODEL}


def _openai(user: str) -> dict:
    from openai import OpenAI

    client = OpenAI()
    resp = client.chat.completions.create(
        model=OPENAI_MODEL,
        max_tokens=400,
        messages=[{"role": "system", "content": SYSTEM}, {"role": "user", "content": user}],
    )
    return {"text": resp.choices[0].message.content.strip(), "model": OPENAI_MODEL}


def _fallback(context: str, note: str | None = None) -> dict:
    text = (
        "Draft for clinician review:\n"
        f"{context}\n"
        "Recommended next step: review and approve the action below. "
        "(Generated by Loop's deterministic fallback — add an LLM key for richer wording.)"
    )
    if note:
        text += f"\n[{note}]"
    return {"text": text, "model": "fallback"}
